apiVersion: v1
kind: Service
metadata:
  name: tictactoe-service
spec:
  type: NodePort
  selector:
    app: tictactoe
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
